version: 2

python:
  install:
    - requirements: ./docs/requirements.txt
    - requirements: requirements.txt

build:
  os: ubuntu-20.04
  tools:
    python: "3.13"

sphinx:
  configuration: docs/conf.py
